spring:
  datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/todo
   username: todo
   password: password

  h2:
    console:
      enabled: true

debug: true